### ISSUE TITLE
Trino connector adding https by default

### ISSUE THREAD

**Issue by ashish135906** [CreativeDataEU/PowerBITrinoConnector#32]
i am trying to connect to my trino server hosted on k8. it is currently using the http protocol. however i am having trouble connecting to it from the power bi desktop as i can see it is adding https by default bfore the host address.

**Comment by pichlerpa** [comment]
Hey, that's not quite correct, the connector doesn't add "https://" by default. It actually depends on the authentication type used in Power BI. If it's Anonymous/Implicit, then "http://" is added before the host otherwise "https://":

https://github.com/CreativeDataEU/PowerBITrinoConnector/blob/917c0dca6ff94c88680331351c760f2df4bc00a2/Trino/Trino.pq#L71

**Comment by ashish135906** [comment]
yes. Thank you for the reply. i was able to change the code and generate a new .mez for our case.
